-- Settings table Alter
ALTER TABLE `settings` ADD `google_analytics` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `sms_date_format`;
ALTER TABLE `settings` ADD `front_logo` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `logo`;
ALTER TABLE `settings` ADD `registration_date` DATE NULL AFTER `school_name`;
ALTER TABLE `settings` DROP `school_geocode`;
ALTER TABLE `settings` ADD `school_lat` VARCHAR(100) NULL AFTER `school_fax`, ADD `school_lng` VARCHAR(100) NULL AFTER `school_lat`;
ALTER TABLE `settings` ADD `about_text` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `google_analytics`, ADD `about_image` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `about_text`;
ALTER TABLE `settings` ADD `academic_year_id` INT(11) NULL AFTER `session_end_month`;

-- guardian_feedbacks

CREATE TABLE `guardian_feedbacks` (
  `id` int(11) NOT NULL, 
  `guardian_id` int(11) NOT NULL,
  `feedback` text NOT NULL,
  `is_publish` tinyint(1) NOT NULL,
  `status` tinyint(1) NOT NULL,
  `created_by` int(11) NOT NULL,
  `modified_by` int(11) NOT NULL,
  `created_at` datetime NOT NULL,
  `modified_at` datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


ALTER TABLE `guardian_feedbacks`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `guardian_feedbacks`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;


-- Pages table alter
ALTER TABLE `pages` ADD `page_location` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `id`;
ALTER TABLE `pages` DROP `page_name`;


-- gallery table alter 
ALTER TABLE `galleries` DROP `image`;

-- news table alter
ALTER TABLE `news` ADD `is_view_on_web` TINYINT(1) NOT NULL DEFAULT '0' AFTER `news`;

-- Holidays table alter
ALTER TABLE `holidays` ADD `is_view_on_web` TINYINT(1) NOT NULL DEFAULT '0' AFTER `note`;

-- Notice table alter
ALTER TABLE `notices` ADD `is_view_on_web` TINYINT(1) NOT NULL DEFAULT '0' AFTER `notice`;

-- Event table alter
ALTER TABLE `events` ADD `is_view_on_web` TINYINT(1) NOT NULL DEFAULT '0' AFTER `note`;


-- income head table alter
ALTER TABLE `income_heads` DROP `academic_year_id`;

-- Language table alter --
INSERT INTO `languages` (`id`, `label`, `english`, `bengali`, `spanish`, `arabic`, `hindi`, `urdu`, `chinese`, `japanese`, `portuguese`, `russian`, `french`, `korean`, `german`, `italian`, `thai`, `hungarian`, `dutch`, `latin`, `indonesian`, `turkish`, `greek`, `persian`, `malay`, `telugu`, `tamil`, `gujarati`, `polish`, `ukrainian`, `panjabi`, `romanian`, `burmese`, `yoruba`, `hausa`) VALUES
(819, 'registration', 'Registration', 'নিবন্ধন', 'Registro', 'التسجيل', 'पंजीकरण', 'رجسٹریشن', '注册', '登録', 'Cadastro', 'Постановка на учет', 'enregistrement', '기재', 'Anmeldung', 'Registrazione', 'การลงทะเบียน', 'Bejegyzés', 'registratie', 'Registration', 'Pendaftaran', 'kayıt', 'Εγγραφή', 'ثبت', 'Pendaftaran', 'నమోదు', 'பதிவு', 'નોંધણી', 'Rejestracja', 'Реєстрація', 'ਰਜਿਸਟਰੇਸ਼ਨ', 'Înregistrare', 'မှတ်ပုံတင်ခြင်း', 'Iforukọ', 'Rijistar'),
(820, 'feedback', 'Feedback', 'প্রতিক্রিয়া', 'Realimentación', 'ردود الفعل', 'प्रतिक्रिया', 'تاثرات', '反馈', 'フィードバック', 'Comentários', 'Обратная связь', 'Retour d\'information', '피드백', 'Feedback', 'Risposta', 'ผลตอบรับ', 'Visszacsatolás', 'terugkoppeling', 'feedback', 'Umpan balik', 'geri bildirim', 'Ανατροφοδότηση', 'بازخورد', 'Maklumbalas', 'అభిప్రాయం', 'பின்னூட்டம்', 'પ્રતિક્રિયા', 'Sprzężenie zwrotne', 'Зворотній зв\'язок', 'ਸੁਝਾਅ', 'Parere', 'တုံ့ပြန်ချက်', 'Idahun', 'Feedback'),
(821, 'super_admin', 'Super Admin', 'সুপার অ্যাডমিন', 'Super admin', 'مشرف متميز', 'सुपर व्यवस्थापक', 'سپر ایڈمن', '超级管理员', 'スーパー管理者', 'Super Admin', 'Супер администратор', 'Super Admin', '수퍼 관리자', 'höchster Vorgesetzter', 'Super Admin', 'ผู้ดูแลระบบขั้นสูง', 'Super Admin', 'Superbeheerder', 'super Maecenas et ipsum', 'Admin Super', 'Süper Yönetici', 'Super Admin', 'مدیر فوق العاده', 'Super Admin', 'సూపర్ అడ్మిన్', 'சூப்பர் நிர்வாகம்', 'સુપર એડમિન', 'Superadministrator', 'Супер адміністратор', 'ਸੁਪਰ ਐਡਮਿਨ', 'Super Admin', 'စူပါအဒ်မင်', 'Super abojuto', 'Super Admin'),
(822, 'is_publish', 'Is Publish?', 'প্রকাশ করা হয়?', 'Es publicar?', 'هل تنشر؟', 'प्रकाशित है?', 'شائع کیا ہے؟', '发布了吗？', 'パブリッシュですか？', 'É publicar?', 'Опубликован?', 'Est Publier?', '게시 하시겠습니까?', 'Ist Veröffentlichen?', 'È pubblico?', 'เผยแพร่แล้วหรือไม่?', 'Publikál?', 'Is publiceren?', 'Auditum est?', 'Apakah Publikasikan?', 'Yayınlanıyor mu?', 'Είναι η δημοσίευση;', 'انتشار است؟', 'Adakah Terbitkan?', 'ప్రచురించాలా?', 'வெளியிட வேண்டுமா?', 'પ્રકાશિત છે?', 'Czy publikujesz?', 'Опублікувати?', 'ਕੀ ਪਬਲਿਸ਼ ਹੈ?', 'Este publicat?', 'Publish သလဲ?', 'Ṣe Atọjade?', 'Ana Buga?'),
(823, 'location', 'Location', 'অবস্থান', 'Ubicación', 'موقعك', 'स्थान', 'مقام', '地点', 'ロケーション', 'Localização', 'Место нахождения', 'Emplacement', '위치', 'Ort', 'Posizione', 'ที่ตั้ง', 'Elhelyezkedés', 'Plaats', 'Location', 'Lokasi', 'yer', 'Τοποθεσία', 'محل', 'Lokasi', 'స్థానం', 'இருப்பிடம்', 'સ્થાન', 'Lokalizacja', 'Розташування', 'ਸਥਾਨ', 'Locație', 'တည်နေရာ', 'Ipo', 'Yanayi'),
(824, 'header', 'Header', 'হেডার', 'Encabezamiento', 'رأس', 'हैडर', 'ہیڈر', '头', 'ヘッダ', 'Cabeçalho', 'заголовок', 'Entête', '머리글', 'Header', 'Intestazione', 'ส่วนหัว', 'Fejléc', 'hoofd', 'header', 'Header', 'Başlık', 'Επί κεφαλής', 'سرتیتر', 'Kepala', 'శీర్షిక', 'தலைப்பு', 'હેડર', 'nagłówek', 'Заголовок', 'ਹੈਡਰ', 'Antet', 'header', 'Akọsori', 'Rubuta'),
(825, 'brand', 'Brand', 'ব্র্যান্ড', 'Marca', 'علامة تجارية', 'ब्रांड', 'برانڈ', '牌', 'ブランド', 'Marca', 'марка', 'Marque', '상표', 'Marke', 'Marca', 'ส่วนหัว', 'Márka', 'Merk', 'Brand', 'Merek', 'Marka', 'Μάρκα', 'نام تجاری', 'Jenama', 'బ్రాండ్', 'பிராண்ட்', 'બ્રાન્ડ', 'Marka', 'Бренд', 'ਬ੍ਰਾਂਡ', 'Marca', 'အမှတ်တံဆိပ်', 'Brand', 'Alamar'),
(826, 'google_analytics', 'Google Analytics', 'গুগল এনালিটিক্স', 'Google analitico', 'تحليلات كوكل', 'गूगल विश्लेषिकी', 'گوگل تجزیہ کار', '谷歌分析', 'グーグルアナリティクス', 'Google Analytics', 'Гугл Аналитика', 'Google Analytics', 'Google 애널리틱스', 'Google Analytics', 'statistiche di Google', 'Google Analytics', 'A Google Analytics', 'Google Analytics', 'Google Analytics', 'Google Analytics', 'Google Analytics', 'Google Analytics', 'تجزیه و تحلیل ترافیک گوگل', 'Google Analytics', 'గూగుల్ విశ్లేషణలు', 'கூகுள் அனலிட்டிக்ஸ்', 'ગૂગલ ઍનલિટિક્સ', 'Google Analytics', 'Google Analytics', 'ਗੂਗਲ ਵਿਸ਼ਲੇਸ਼ਣ', 'Google Analytics', 'Google Analytics', 'Atupale Google', 'Google Analytics'),
(827, 'have_any_question', 'Have you any question?', 'আপনার কোন প্রশ্ন আছে?', '¿Tienes alguna pregunta?', 'هل لديك أي سؤال؟', 'क्या आपका कोई सवाल है?', 'کیا آپ کا کوئی سوال ہے', '你有什么问题吗？', '何か質問ありますか？', 'Você tem alguma pergunta?', 'У вас есть вопрос?', 'Avez-vous une question?', '질문 있니?', 'Hast du eine Frage?', 'Hai qualche domanda?', 'คุณมีคำถามหรือไม่?', 'Kérdése van?', 'Heb je een vraag?', 'Have vos interrogare?', 'Apakah Anda punya pertanyaan?', 'Bir sorunuz var mı?', 'Έχετε κάποια ερώτηση;', 'آیا شما هر گونه سوال', 'Adakah anda mempunyai soalan?', 'మీకు ఏదైనా ప్రశ్న ఉందా?', 'உங்களிடம் ஏதாவது கேள்வி இருக்கிறதா?', 'શું તમને કોઈ પ્રશ્ન છે?', 'Masz jakieś pytanie?', 'У вас є якесь питання?', 'ਕੀ ਤੁਹਾਨੂੰ ਕੋਈ ਸਵਾਲ ਹੈ?', 'Aveți vreo întrebare?', 'သင်သည်မည်သည့်မေးခွန်းရှိပါသလား?', 'Ṣe o ni eyikeyi ibeere?', 'Shin kuna da wata tambaya?'),
(828, 'call_us', 'Call us', 'আমাদের কল করুন', 'Llamanos', 'اتصل بنا', 'हमें बुलाओ', 'ہمیں بلائیں', '打电话给我们', 'お電話ください', 'Ligue para nós', 'Позвоните нам', 'Appelez nous', '전화주세요.', 'Ruf uns an', 'Chiamaci', 'โทรหาเรา', 'Hívjon bennünket', 'Bel ons', 'nos voca', 'Hubungi kami', 'Bizi arayın', 'Καλέστε μας', 'با ما تماس بگیرید', 'Hubungi kami', 'మాకు కాల్ చేయండి', 'எங்களை அழை', 'અમને કૉલ કરો', 'Zadzwoń do nas', 'Зателефонуйте нам', 'ਸਾਨੂੰ ਕਾਲ ਕਰੋ', 'Sună-ne', 'ကျွန်တော်တို့ကို Call', 'Pe wa', 'Kira mana'),
(829, 'email_us', 'Email us', 'আমাদেরকে ইমেইল করুন', 'Envíenos un correo electrónico', 'أرسل لنا', 'हमे ईमेल करे', 'ہمیں ای میل کریں', '电邮我们', '私達に電子メールを送り', 'Envia-nos um email', 'Свяжитесь с нами по электронной почте', 'Envoyez-nous un email', '이메일 문의', 'Schreiben Sie uns eine E-Mail', 'Mandaci una email', 'ส่งอีเมลถึงเรา', 'Küldj egy emailt nekünk', 'Email ons', 'email us', 'Email kami', 'Bize e-posta', 'Στείλτε μας email', 'به ما ایمیل بزنید', 'Email kami', 'మాకు ఇమెయిల్ చేయండి', 'எங்களுக்கு மின்னஞ்சல்', 'અમને ઇમેઇલ કરો', 'Wyślij do nas e-mail', 'Напишіть нам', 'ਸਾਨੂੰ ਈਮੇਲ ਕਰੋ', 'Trimite-ti-ne un e-mail', 'ကျွန်တော်တို့ကိုအီးမေး', 'Imeeli wa', 'Email mu'),
(830, 'welcome_to', 'Welcome to', 'স্বাগতম', 'Bienvenido a', 'مرحبا بك في', 'में स्वागत', 'میں خوش آمدید', '欢迎来到', 'ようこそ', 'Bem-vindo ao', 'Добро пожаловать в', 'Bienvenue à', '에 오신 것을 환영합니다', 'Willkommen zu', 'Benvenuto a', 'ยินดีต้อนรับสู่', 'Isten hozott a', 'Welkom bij', 'gratam', 'Selamat Datang di', 'Hoşgeldiniz', 'Καλωσόρισες στο', 'خوش آمدید به', 'Selamat datang ke', 'స్వాగతం', 'வரவேற்கிறோம்', 'સ્વાગત', 'Witamy w', 'Ласкаво просимо до', 'ਸਵਾਗਤ ਹੈ', 'Bun venit la', 'မှလှိုက်လှဲစွာကြိုဆိုပါသည်', 'Kaabo si', 'Barka da zuwa'),
(831, 'now', 'Now', 'এখন', 'Ahora', 'الآن', 'अभी व', 'ابھی', '现在', '今', 'Agora', 'Сейчас', 'À présent', '지금', 'Jetzt', 'Adesso', 'ตอนนี้', 'Most', 'Nu', 'autem', 'Sekarang', 'şimdi', 'Τώρα', 'اکنون', 'Sekarang', 'ఇప్పుడు', 'இப்போது', 'હવે', 'Teraz', 'Зараз', 'ਹੁਣ', 'Acum', 'ယခု', 'Bayi', 'Yanzu'),
(832, 'our', 'Our', 'আমাদের', 'Nuestro', 'لنا', 'हमारी', 'ہمارا', '我们的', '私たち', 'Nosso', 'наш', 'Notre', '우리의', 'Unsere', 'Nostro', 'ของเรา', 'a', 'Onze', 'nostrum', 'Kami', 'bizim', 'Μας', 'ما', 'Kami', 'మా', 'எங்கள்', 'અમારું', 'Nasz', 'Наша', 'ਸਾਡਾ', 'Al nostru', 'ကျွန်တော်တို့၏', 'Wa', 'Mu'),
(833, 'facilities', 'Facilities', 'সু্যোগ  সুবিধা', 'Instalaciones', 'مرافق', 'सुविधाएं', 'سہولیات', '设备', '施設', 'Instalações', 'оборудование', 'Installations', '시설', 'Anlagen', 'Strutture', 'สิ่งอำนวยความสะดวก', 'Felszerelés', 'uitrusting', 'facilities', 'Fasilitas', 'tesisler', 'Εγκαταστάσεις', 'امکانات', 'Kemudahan', 'సౌకర్యాలు', 'வசதிகள்', 'સુવિધાઓ', 'Udogodnienia', 'Засоби', 'ਸੁਵਿਧਾਵਾਂ', 'Facilităţi', 'အဆောက်အဦးများ', 'Awọn ohun elo', 'Ayyuka'),
(834, 'experienced', 'Experienced', 'অভিজ্ঞ', 'Experimentado', 'يختبر', 'अनुभव', 'تجربہ کار', '有经验的', '経験豊富な', 'Com experiência', 'опытный', 'Expérimenté', '숙련 된', 'Erfahren', 'Esperto', 'มีประสบการณ์', 'Tapasztalt', 'Ervaren', 'periti', 'Berpengalaman', 'Deneyimli', 'Εμπειρος', 'با تجربه', 'Berpengalaman', 'అనుభవజ్ఞులైన', 'அனுபவமிக்க', 'અનુભવી', 'Doświadczony', 'Досвідчений', 'ਤਜਰਬੇਕਾਰ', 'Cu experienta', 'တွေ့ကြုံ', 'Ti ni iriri', 'Dandana'),
(835, 'achivement', 'Achievement', 'অর্জন', 'Logro', 'موهلات', 'उपलब्धि', 'کامیابی', '成就', '成果', 'Realização', 'Достижение', 'Réussite', '성취', 'Leistung', 'realizzazione', 'ความสำเร็จ', 'Teljesítmény', 'prestatie', 'factum', 'Prestasi', 'Başarı', 'Κατόρθωμα', 'دستاورد', 'Pencapaian', 'అచీవ్మెంట్', 'சாதனையாளர்', 'સિદ્ધિ', 'Osiągnięcie', 'Досягнення', 'ਪ੍ਰਾਪਤੀ', 'Realizare', 'အောင်မြင်ချက်', 'Aseyori', 'Sakamakon'),
(836, 'by', 'By', 'দ্বারা', 'Por', 'بواسطة', 'द्वारा', 'کی طرف سے', '通过', 'によって', 'Por', 'От', 'Par', '으로', 'Durch', 'Di', 'โดย', 'Által', 'Door', 'a', 'Oleh', 'Tarafından', 'Με', 'توسط', 'Oleh', 'ద్వారా', 'மூலம்', 'દ્વારા', 'Przez', 'По', 'ਨਾਲ', 'De', 'အားဖြင့်', 'Nipa', 'By'),
(837, 'what_guardian_say', 'What Guardian Say?', 'গার্ডিয়ান কি বলে?', '¿Qué dice el guardián?', 'ما الوصي قل؟', 'क्या गार्जियन कहते हैं?', 'کیا گارڈین کہتے ہیں؟', '卫报怎么说？', 'ガーディアンは何を言っているの？', 'O que o guardião diz?', 'Что сказал Хранитель?', 'Que dit le gardien?', '가디언이 뭐라 구요?', 'Was Wächter sagen?', 'Che cosa dice il guardiano?', 'อะไร Guardian Say?', 'Milyen Guardian mondja?', 'Welke bewaker zegt?', 'Custos, quid dices?', 'Apa yang dikatakan Guardian?', 'Koruyucu ne diyor?', 'Τι λέει ο Guardian;', 'چه گاردی می گوید؟', 'Apa yang dikatakan Guardian?', 'గార్డియన్ ఏమి చెబుతారు?', 'கார்டியன் என்ன சொல்கிறது?', 'ગાર્ડિયન શું કહે છે?', 'Co mówi strażnik?', 'Що каже гадаю?', 'ਗਾਰਡੀਅਨ ਕੀ ਕਹਿੰਦੇ ਹਨ?', 'Ce spune Guardian?', 'အဘယ်အရာကိုဂါးဒီးယန်းပြောရမည်မှာ,', 'Kini Oluṣọ Kan Sọ?', 'Abin da Guardian Say?'),
(838, 'apply_now_for_your_kid', 'Apply Now for Your Kids', 'আপনার বাচ্চাদের জন্য এখন আবেদন করুন', 'Solicite ahora para sus hijos', 'قدم الآن لأطفالك', 'अपने बच्चों के लिए अभी आवेदन करें', 'اپنے بچوں کے لئے اب درخواست دیں', '立即申请您的孩子', 'あなたの子供たちに今すぐ応募する', 'Inscreva-se agora para seus filhos', 'Применить сейчас для своих детей', 'Appliquez maintenant pour vos enfants', '자녀에게 지금 신청하십시오', 'Bewerben Sie sich jetzt für Ihre Kinder', 'Fai domanda per i tuoi bambini', 'สมัครตอนนี้เพื่อลูกของคุณ', 'Jelentkezz most a gyerekeknek', 'Meld je nu aan voor je kinderen', 'Applicare autem tuus pro Kids', 'Ajukan Sekarang untuk Anak-Anak Anda', 'Çocuklarınız için Şimdi Başvurun', 'Εφαρμόστε τώρα για τα παιδιά σας', 'اکنون برای کودکان خود اعمال کنید', 'Sapukan Sekarang untuk Anak-Anak Anda', 'ఇప్పుడు మీ కిడ్స్ కోసం దరఖాస్తు చేసుకోండి', 'உங்கள் பிள்ளைகளுக்கு இப்போது விண்ணப்பிக்கவும்', 'તમારા બાળકો માટે હવે અરજી કરો', 'Złóż aplikację teraz dla swoich dzieci', 'Застосувати зараз для своїх дітей', 'ਆਪਣੇ ਬੱਚਿਆਂ ਲਈ ਹੁਣੇ ਅਪਲਾਈ ਕਰੋ', 'Aplicați acum pentru copiii dvs.', 'သင့်ရဲ့ကလေးတွေကအဘို့အ Now ကို Apply', 'Ṣe Waye Bayi fun Awọn ọmọ wẹwẹ rẹ', 'Nemi Yanzu Don Yaracenku'),
(839, 'apply', 'Apply', 'আবেদন করুন ', 'Aplicar', 'تطبيق', 'लागू करें', 'درخواست دیں', '应用', '適用', 'Aplique', 'Применять', 'Appliquer', '대다', 'Sich bewerben', 'Applicare', 'ใช้', 'Alkalmaz', 'Van toepassing zijn', 'Applicare', 'Menerapkan', 'Uygulamak', 'Ισχύουν', 'درخواست دادن', 'Memohon', 'వర్తించు', 'விண்ணப்பிக்கவும்', 'અરજી કરો', 'Zastosować', 'Застосувати', 'ਲਾਗੂ ਕਰੋ', 'aplica', 'Apply', 'Waye', 'Aiwatar'),
(840, 'visit', 'Visit', 'পরিদর্শন', 'Visitar', 'يزور', 'पर जाएँ', 'ملاحظہ کریں', '访问', '訪問', 'Visita', 'Визит', 'Visite', '방문', 'Besuch', 'Visita', 'เยือน', 'Látogatás', 'Bezoek', 'visita', 'Mengunjungi', 'Ziyaret etmek', 'Επίσκεψη', 'بازدید', 'Lawati', 'సందర్శించండి', 'வருகை', 'મુલાકાત લો', 'Odwiedzić', 'Відвідайте', 'ਮੁਲਾਕਾਤ', 'Vizita', 'အလည်အပတ်', 'Ṣabẹwo', 'Ziyarci'),
(841, 'publish', 'Publish', 'প্রকাশিত', 'Publicar', 'نشر', 'प्रकाशित करना', 'شائع کریں', '发布', '公開する', 'Publicar', 'Публиковать', 'Publier', '게시', 'Veröffentlichen', 'Pubblicare', 'ประกาศ', 'közzétesz', 'Publiceren', 'publish', 'Menerbitkan', 'Yayınla', 'Δημοσιεύω', 'انتشار', 'Menerbitkan', 'ప్రచురించు', 'வெளியிடு', 'પ્રકાશિત કરો', 'Publikować', 'Опублікувати', 'ਪਬਲਿਸ਼ ਕਰੋ', 'Publica', 'ပုံနှိပ်ထုတ်ဝေ', 'Ṣe atẹjade', 'Buga'),
(842, 'unpublish', 'Unpublish', 'অপ্রকাশিত', 'No publicar', 'إلغاء النشر', 'अप्रकाशित', 'غیر اشاعت شدہ', '取消发布', '公開しない', 'Cancelar publicação', 'Отменить публикацию', 'Annuler la publication', '게시 취소', 'Veröffentlichung rückgängig machen', 'Non pubblicato', 'ยกเลิกการเผยแพร่', 'közzétételének', 'Publicatie ongedaan maken', 'Unpublishway', 'Batalkan publikasi', 'Yayından Kaldır', 'Κατάργηση δημοσίευσης', 'لغو انتشار', 'Tidak dapat menerbitkan', 'ప్రచురించని', 'வெளியிடாதே', 'અનપ્રકાશિત', 'Cofnij publikację', 'Скасувати публікацію', 'ਅਪ੍ਰਕਾਸ਼ਿਤ', 'Anulați publicarea', 'မထုတ်ဝေရသေးသော', 'Aṣejade', 'Unpublish'),
(843, 'detail', 'Detail', 'বিস্তারিত', 'Detalle', 'التفاصيل', 'विस्तार', 'تفصیل', '详情', '詳細', 'Detalhe', 'подробность', 'Détail', '세부 묘사', 'Detail', 'Dettaglio', 'รายละเอียด', 'Részlet', 'Detail', 'detail', 'Detail', 'detay', 'Λεπτομέρεια', 'جزئیات', 'Terperinci', 'వివరాలు', 'விவரம்', 'વિગતવાર', 'Szczegół', 'Подробиці', 'ਵੇਰਵੇ', 'Detaliu', 'အသေးစိတ်', 'Apejuwe', 'Detail'),
(844, 'school_lat', 'Latitude', 'অক্ষাংশ', 'Latitud', 'خط العرض', 'अक्षांश', 'طول', '纬度', '緯度', 'Latitude', 'широта', 'Latitude', '위도', 'Breite', 'Latitudine', 'ละติจูด', 'Szélességi kör', 'Breedtegraad', 'latitudo', 'Lintang', 'Enlem', 'Γεωγραφικό πλάτος', 'عرض جغرافیایی', 'Latitud', 'అక్షాంశం', 'அட்சரேகை', 'અક્ષાંશ', 'Szerokość', 'Широта', 'ਵਿਥਕਾਰ', 'Latitudine', 'လတီ္တတွဒ်', 'Iwọn', 'Latitude'),
(845, 'school_lng', 'Longitude', 'দ্রাঘিমা', 'Longitud', 'خط الطول', 'देशान्तर', 'لمبائی', '经度', '経度', 'Longitude', 'Долгота', 'Longitude', '경도', 'Längengrad', 'Longitudine', 'ลองจิจูด', 'Hosszúság', 'Lengtegraad', 'longitudo', 'Garis bujur', 'Boylam', 'Γεωγραφικό μήκος', 'عرض جغرافیایی', 'Longitud', 'రేఖాంశం', 'தீர்க்கரேகை', 'રેખાંશ', 'Długość geograficzna', 'Довгота', 'ਲੰਬਕਾਰ', 'Longitudine', 'လောင်ဂျီတွဒ်', 'Gunitude', 'Longitude'),
(846, 'galleries', 'Galleries', 'গ্যালারী', 'Galerias', 'المعارض', 'गैलरी', 'گیلریوں', '画廊', 'ギャラリー', 'Galerias', 'галереи', 'Galeries', '갤러리', 'Galerien', 'Gallerie', 'แกลลอรี่', 'galériák', 'Galleries', 'supportabant porticus', 'Galeri', 'Galeriler', 'Γκαλερί', 'گالری ها', 'Galeri', 'గ్యాలరీలు', 'காட்சியகங்கள்', 'ગેલેરીઓ', 'Galerie', 'Галереї', 'ਗੈਲਰੀਆਂ', 'Galerii', 'ပြခန်း', 'Awọn aworan aworan', 'Galleries'),
(847, 'events', 'Events', 'ইভেন্টস', 'Eventos', 'أحداث', 'आयोजन', 'تقریبات', '活动', 'イベント', 'Eventos', 'События', 'Événements', '이벤트', 'Veranstaltungen', 'eventi', 'เหตุการณ์ที่เกิดขึ้น', 'Események', 'Evenementen', 'Events', 'Acara', 'Olaylar', 'Εκδηλώσεις', 'مناسبت ها', 'Peristiwa', 'ఈవెంట్స్', 'நிகழ்வுகள்', 'ઘટનાઓ', 'Wydarzenia', 'Події', 'ਸਮਾਗਮ', 'Evenimente', 'ဖြစ်ရပ်များ', 'Awọn iṣẹlẹ', 'Events'),
(848, 'notices', 'Notices', 'নোটিশস', 'Avisos', 'إشعارات', 'नोटिस', 'نوٹس', '通告', '通知', 'Avisos', 'Извещения', 'Les avis', '공지 사항', 'Bemerkungen', 'Avvisi', 'การบอกกล่าว', 'közlemények', 'Mededelingen', 'III', 'Pemberitahuan', 'Uyarılar', 'Ειδοποιήσεις', 'اطلاعیه ها', 'Notis', 'నోటీసులు', 'அறிவிப்புகள்', 'સૂચનાઓ', 'Powiadomienia', 'Сповіщення', 'ਸੂਚਨਾਵਾਂ', 'Notificări', 'သတိပေးချက်များ', 'Awọn akiyesi', 'Sanarwa'),
(849, 'holidays', 'Holidays', 'হলিডেজ', 'Vacaciones', 'العطل', 'छुट्टियां', 'چھٹیوں', '假期', '休日', 'Feriados', 'каникулы', 'Vacances', '휴가', 'Ferien', 'Vacanze', 'วันหยุด', 'Ünnepek', 'Vakantie', 'feriae', 'Liburan', 'Bayram', 'Διακοπές', 'تعطیلات', 'Cuti', 'సెలవులు', 'விடுமுறை', 'રજાઓ', 'Wakacje', 'Свята', 'ਛੁੱਟੀਆਂ', 'concediu', 'အားလပ်ရက်', 'Awọn isinmi', 'Ranaku Masu Tsarki'),
(850, 'pls_remove_child_data', 'Please delete child data before delete this.', 'এই ডাটা  মুছে ফেলার আগে প্লিজ ডিলিট চাইল্ড ডাটা', 'Por favor, elimine los datos secundarios antes de eliminar esto.', 'يرجى حذف البيانات الفرعية قبل حذفها.', 'इसे हटाने से पहले कृपया बाल डेटा हटाएं।', 'براہ کرم اس کو حذف کرنے سے قبل بچے کے ڈیٹا کو حذف کریں.', '删除之前请删除子数据。', '削除する前に子データを削除してください。', 'Por favor, apague os dados da criança antes de deletar isto.', 'Удалите дочерние данные перед удалением.', 'Veuillez supprimer les données enfants avant de supprimer ceci.', '삭제하기 전에 하위 데이터를 삭제하십시오.', 'Bitte löschen Sie untergeordnete Daten, bevor Sie diese löschen.', 'Si prega di cancellare i dati figlio prima di eliminarlo.', 'โปรดลบข้อมูลเด็กก่อนลบข้อมูลนี้', 'Kérjük, törölje a gyermekadatokat a törlés előtt.', 'Wis onderliggende gegevens voordat u deze verwijdert.', 'Delete hoc in conspectu delete notitia puero placet.', 'Hapus data anak sebelum menghapus ini.', 'Lütfen bunu silmeden önce çocuk verilerini silin', 'Διαγράψτε τα δεδομένα παιδιού πριν διαγράψετε αυτό το θέμα.', 'لطفا قبل از حذف این اطلاعات فرزند را حذف کنید.', 'Sila padamkan data kanak-kanak sebelum memadamkannya.', 'దీన్ని తొలగించడానికి ముందు పిల్లల డేటాను తొలగించండి.', 'இதை நீக்குவதற்கு முன் குழந்தைத் தரவை நீக்குக.', 'કૃપા કરીને આને કાઢી નાખતા પહેલા બાળ ડેટા કાઢી નાખો.', 'Usuń dane podrzędne, zanim je usuniesz.', 'Будь ласка, видаліть дочірні дані, перш ніж видалити це.', 'ਕਿਰਪਾ ਕਰਕੇ ਇਸਨੂੰ ਮਿਟਾਉਣ ਤੋਂ ਪਹਿਲਾਂ ਬੱਚੇ ਦਾ ਡੇਟਾ ਮਿਟਾਓ.', 'Ștergeți datele copilului înainte de a șterge acest lucru.', 'မတိုင်မှီကဒီကိုဖျက်ကလေးက data တွေကိုဖျက်ပစ်ပါ။', 'Jọwọ pa awọn ọmọ ọmọkunrin rẹ ṣaaju ki o to paarẹ.', 'Da fatan a share bayanan jariri kafin a share wannan.');



INSERT INTO `languages` (`id`, `label`, `english`, `bengali`, `spanish`, `arabic`, `hindi`, `urdu`, `chinese`, `japanese`, `portuguese`, `russian`, `french`, `korean`, `german`, `italian`, `thai`, `hungarian`, `dutch`, `latin`, `indonesian`, `turkish`, `greek`, `persian`, `malay`, `telugu`, `tamil`, `gujarati`, `polish`, `ukrainian`, `panjabi`, `romanian`, `burmese`, `yoruba`, `hausa`) 
VALUES (851, 'industry_type', 'Industry Type', 'ইন্ডাস্ট্রি টাইপ', 'Tipo de industria', 'نوع الصناعة', 'उद्योग के प्रकार', 'صنعت کی قسم', '行业类型', '業種別', 'tipo industrial', 'Тип промышленности', 'type dindustrie', '업종', 'Branchentyp', 'Tipo dindustria', 'ประเภทอุตสาหกรรม', 'Ipari típus', 'industrie type', 'Type Industry', 'Jenis Industri', 'Endüstri Tipi', 'Τύπος βιομηχανίας', 'نوع صنعت', 'Jenis Industri', 'పరిశ్రమ పద్ధతి', 'தொழில் வகை', 'ઉદ્યોગ પ્રકાર', 'typ przemysłu', 'Тип промисловості', 'ਉਦਯੋਗ ਕਿਸਮ', 'tipul industriei', 'စက်မှုအမျိုးအစား', 'Iru iṣẹ Iru', 'Masana antu');

ALTER TABLE `payment_settings` ADD `paytm_industry_type` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `paytm_merchant_website`;

ALTER TABLE `purchase` ADD PRIMARY KEY(`id`);

ALTER TABLE `settings` ADD `map_api_key` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `google_analytics`;
